name = "chatelherault-rc-website"
compatibility_date = "2026-03-29"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "chatelherault_auth"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
