name = "chatelherault-rc-website"
compatibility_date = "2026-03-29"
main = "worker.js"

routes = [
	{ pattern = "www.chatelheraultrc.com", zone_name = "chatelheraultrc.com", custom_domain = true },
	{ pattern = "chatelheraultrc.com", zone_name = "chatelheraultrc.com", custom_domain = true },
]

[assets]
directory = "."
binding = "ASSETS"

[vars]
GITHUB_REPO_OWNER = "Frazmcc"
GITHUB_REPO_NAME = "chatelherault-rc-website"
GITHUB_BRANCH = "main"
CONTACT_EMAIL = "contact@chatelheraultrc.com"
CONTACT_FROM_EMAIL = "contact@chatelheraultrc.com"
TURNSTILE_SITE_KEY = "0x4AAAAAAC0oUDXNzCW-4deY"

[[d1_databases]]
binding = "DB"
database_name = "chatelherault_auth"
database_id = "1731c3f6-84d0-4c75-bc64-1ee525e10054"
